# version: "3.8"
# services:
#   nginx:
#     build: .
#     container_name: stream-nginx
#     ports:
#       - "1935:1935"   # RTMP (OBS -> server)
#       - "5173:5173"   # HTTP (browser/VLC -> HLS)
#     volumes:
#       - ./html:/var/www/html:ro
#       - hls-data:/var/www/hls
#     restart: unless-stopped

# volumes:
#   hls-data:


version: "3.8"

services:
  nginx:
    build: .
    container_name: stream-nginx
    ports:
      - "1935:1935"   # RTMP (OBS -> server)
      - "8080:8080"   # HTTP (HLS player)
    volumes:
      - ./html:/var/www/html:ro
      - hls-data:/var/www/hls
    restart: unless-stopped

volumes:
  hls-data:
